spring:
  data:
    mongodb:
      #uri: mongodb://fox:fox@192.168.65.174:27017/test?authSource=admin
      #uri等同于下面的配置
      #database: test
      #host: 192.168.65.174
      #port: 27017
      #username: fox
      #password: fox
      #authentication-database: admin

      #复制集  https://docs.mongodb.com/manual/reference/connection-string/
      uri: mongodb://fox:fox@192.168.65.174:28017,192.168.65.174:28018,192.168.65.174:28019/test?authSource=admin&replicaSet=rs0


logging:
  level:
    org.springframework.data.mongodb: debug


